pipeline:
  build:
    image: termoshtt/rust
    commands:
      - cargo build -v
      - cargo test -v

  example:
    image: termoshtt/rust
    commands:
      - cd numpy-example
      - cargo build
      - python example.py
