pipeline:
  build:
    image: termoshtt/rust
    commands:
      - cargo build -v
      - cargo test -v

  example:
    image: termoshtt/rust
    commands:
      - cd example
      - pip install -r requirements.txt
      - python setup.py develop
      - ./test.py
