language: rust
sudo: required

rust:
  - stable
  - beta
  - nightly

os:
  - linux

cache: cargo

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo test

addons:
  apt:
    packages:
      - python3-dev
      - python3-numpy

env:
  - RUST_BACKTRACE=1
