[package]
name = "numpy"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[dependencies]
cpython = "0.1"
python3-sys = "0.1"

[dependencies.numpy-sys]
version = "0.1"
path = "numpy-sys"

