[package]
name = "numpy"
version = "0.4.0-alpha.1"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

description = "Rust binding of NumPy C-API"
documentation = "https://docs.rs/numpy/"
repository = "https://github.com/termoshtt/rust-numpy"
keywords = ["numpy", "python", "binding"]
license-file = "LICENSE"

[dependencies]
cfg-if = "0.1.6"
libc = "0.2.43"
num-complex = "0.2.1"
num-traits = "0.2.6"
ndarray = "0.12.0"
pyo3 = "0.5.0"

[features]
# In default setting, python version is automatically detected
default = []
# Use this feature when building python2 binding.
python2 = ["pyo3/python2"]
# Use this feature when building python3 binding.
python3 = ["pyo3/python3"]

