[package]
name = "numpy"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

description = "Rust binding of NumPy C-API"
repository = "https://github.com/termoshtt/rust-numpy"
keywords = ["numpy", "python", "binding"]
license-file = "LICENSE"

[dependencies]
libc = "0.2"
cpython = "0.1"
python3-sys = "0.1"
