[package]
name = "numpy"
version = "0.2.1"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

description = "Rust binding of NumPy C-API"
documentation = "https://docs.rs/numpy/"
repository = "https://github.com/termoshtt/rust-numpy"
keywords = ["numpy", "python", "binding"]
license-file = "LICENSE"

[dependencies]
libc = "0.2"
num-complex = "0.1"
ndarray = "0.10"

[dependencies.pyo3]
git = "http://github.com/termoshtt/pyo3"
branch = "pyobject_macros"
version = "0.2"
