[package]
name = "numpy-sys"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

build = "build.rs"
links = "numpy_c_api"

[dependencies]
libc = "0.2.21"
python3-sys = "0.1.3"

[build-dependencies]
gcc = "0.3"
